# Generated by Django 5.2.16 on 2026-07-30 14:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RESPONSABLE_AGENCE', "Responsable d'agence"), ('CAISSIER', 'Caissier')], db_index=True, help_text="Rôle de l'utilisateur : détermine son périmètre d'accès (EF-9.2 à EF-9.4).", max_length=20)),
                ('telephone', models.CharField(blank=True, help_text="Numéro de téléphone professionnel de l'utilisateur.", max_length=30)),
                ('agence', models.ForeignKey(blank=True, help_text="Agence de rattachement. Obligatoire pour un Responsable d'agence ou un Caissier ; laisser vide pour un Admin (accès à toutes les agences).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='general.agence')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.utilisateur',),
            managers=[
                ('objects', users.models.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caissier',
            fields=[
            ],
            options={
                'verbose_name': 'Caissier',
                'verbose_name_plural': 'Caissiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.utilisateur',),
            managers=[
                ('objects', users.models.CaissierManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAgence',
            fields=[
            ],
            options={
                'verbose_name': "Responsable d'agence",
                'verbose_name_plural': "Responsables d'agence",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.utilisateur',),
            managers=[
                ('objects', users.models.ResponsableAgenceManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='users_utili_role_ac60e1_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['agence', 'role'], name='users_utili_agence__bd9f8d_idx'),
        ),
    ]
