# Generated by Django 5.2.16 on 2026-07-30 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('nom', models.CharField(help_text="Raison sociale affichée sur les reçus et l'en-tête de l'application.", max_length=150)),
                ('logo', models.ImageField(blank=True, help_text="Logo affiché sur les reçus et l'en-tête de l'application.", null=True, upload_to='entreprise/')),
                ('slogan', models.CharField(blank=True, help_text="Slogan de l'entreprise.", max_length=255)),
                ('adresse', models.CharField(blank=True, help_text='Adresse du siège social.', max_length=255)),
                ('telephone', models.CharField(blank=True, help_text='Téléphone de contact principal.', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Email de contact principal.', max_length=254)),
                ('site_web', models.URLField(blank=True, help_text="Site web de l'entreprise.")),
                ('tax_id', models.CharField(blank=True, help_text='Numéro fiscal / identifiant contribuable, affiché sur les reçus.', max_length=50)),
                ('devise', models.CharField(default='FCFA', help_text="Symbole monétaire utilisé dans toute l'application.", max_length=10)),
                ('note_pied_page', models.TextField(blank=True, help_text='Note affichée en bas des reçus (conditions, remerciements...).')),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('nom', models.CharField(help_text="Nom commercial de l'agence.", max_length=150)),
                ('slug', models.SlugField(blank=True, help_text="Identifiant unique de l'agence utilisé dans les URLs (ex: /agences/<slug>/) à la place de l'UUID, notamment pour les liens visités par un Responsable d'agence ou un Caissier après connexion. Généré automatiquement à partir du nom si laissé vide.", max_length=170, unique=True)),
                ('adresse', models.CharField(blank=True, help_text="Adresse physique de l'agence.", max_length=255)),
                ('telephone', models.CharField(blank=True, help_text="Numéro de téléphone de contact de l'agence.", max_length=30)),
                ('actif', models.BooleanField(db_index=True, default=True, help_text="Une agence désactivée est exclue des écrans de vente/POS mais reste visible dans l'historique et les rapports (EF-1.3).")),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['nom'], name='general_age_nom_5fc249_idx'), models.Index(fields=['actif', 'nom'], name='general_age_actif_c31689_idx')],
            },
        ),
    ]
