# Generated by Django 5.2.16 on 2026-07-30 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('quantite', models.PositiveIntegerField(help_text='Quantité vendue.')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix unitaire figé au moment de la vente (copié depuis ProduitAgence), pour ne pas modifier l'historique si le prix change ensuite (EF-7.4).", max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, help_text='quantité x prix_unitaire, calculé par signal (EF-13.4).', max_digits=12)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('numero_recu', models.CharField(db_index=True, help_text='Numéro unique du reçu, utilisé pour la recherche (EF-8.3).', max_length=40, unique=True)),
                ('fichier_pdf', models.FileField(blank=True, help_text='Version PDF téléchargeable du reçu (EF-8.2).', null=True, upload_to='recus/')),
                ('date_generation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de génération du reçu.')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('nom', models.CharField(help_text='Nom complet du client.', max_length=150)),
                ('telephone', models.CharField(db_index=True, help_text="Numéro de téléphone : clé naturelle utilisée pour éviter les doublons lorsqu'un même client est saisi avec une orthographe de nom différente (EF-6.4).", max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email du client (optionnel).', max_length=254)),
                ('adresse', models.CharField(blank=True, help_text='Adresse du client (optionnelle).', max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['nom'], name='sales_clien_nom_5de951_idx')],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('remise', models.DecimalField(decimal_places=2, default=0, help_text='Montant de la remise appliquée à la commande (EF-7.2).', max_digits=12)),
                ('taxe', models.DecimalField(decimal_places=2, default=0, help_text='Montant de la taxe appliquée à la commande (EF-7.2).', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total de la commande, recalculé par signal à partir des lignes (EF-13.4).', max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('AUTRE', 'Autre')], help_text='Mode de paiement utilisé (EF-7.2).', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('REMBOURSEE', 'Remboursée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', help_text='Cycle de vie de la commande (EF-7.5).', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de la vente.')),
                ('agence', models.ForeignKey(help_text='Agence dans laquelle la vente a été réalisée.', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='general.agence')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
