# Generated by Django 5.2.16 on 2026-07-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='caissier',
            field=models.ForeignKey(help_text='Caissier ayant réalisé la vente.', limit_choices_to={'role': 'CAISSIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_realisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Client de la vente. Facultatif : une vente 'client de passage' est valide (EF-6.1).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='sales.client'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(help_text='Commande à laquelle appartient cette ligne.', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sales.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(help_text='Produit vendu.', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='products.produit'),
        ),
        migrations.AddField(
            model_name='recu',
            name='commande',
            field=models.OneToOneField(help_text='Commande terminée associée à ce reçu (relation un-à-un, EF-8.1).', on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='sales.commande'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['agence', 'statut', 'date'], name='sales_comma_agence__29f1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['caissier', 'date'], name='sales_comma_caissie_2d5080_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['commande'], name='sales_ligne_command_29343b_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['produit'], name='sales_ligne_produit_8f146e_idx'),
        ),
    ]
