# Generated by Django 5.2.16 on 2026-07-30 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('nom', models.CharField(help_text='Nom de la catégorie.', max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Identifiant lisible utilisé dans les URLs, généré automatiquement à partir du nom si laissé vide.', max_length=170, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Image illustrant la catégorie.', null=True, upload_to='categories/')),
                ('actif', models.BooleanField(db_index=True, default=True, help_text="Une catégorie désactivée n'apparaît plus dans le catalogue.")),
                ('parent', models.ForeignKey(blank=True, help_text='Catégorie parente, pour créer une hiérarchie imbriquée (EF-2.2).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='products.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('nom', models.CharField(db_index=True, help_text='Nom commercial du produit.', max_length=200)),
                ('sku', models.CharField(help_text='SKU / code-barres unique du produit (EF-3.1).', max_length=64, unique=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, help_text="Prix d'achat / coût de revient du produit. Commun à toutes les agences (contrairement au prix de vente, fixé par agence).", max_digits=12)),
                ('prix_vente_defaut', models.DecimalField(decimal_places=2, help_text="Prix de vente par défaut, utilisé pour pré-remplir le prix d'une nouvelle fiche ProduitAgence. Chaque agence peut ensuite fixer son propre prix de vente (EF-4.2).", max_digits=12)),
                ('unite', models.CharField(default='unité', help_text='Unité de vente (pièce, kg, litre...).', max_length=30)),
                ('image', models.ImageField(blank=True, help_text='Photo du produit.', null=True, upload_to='produits/')),
                ('description', models.TextField(blank=True, help_text='Description commerciale du produit.')),
                ('actif', models.BooleanField(db_index=True, default=True, help_text='Un produit désactivé ne peut plus être proposé par une agence.')),
                ('categorie', models.ForeignKey(help_text='Catégorie à laquelle appartient ce produit.', on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='products.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProduitAgence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix de vente pratiqué par cette agence pour ce produit. Peut différer du prix_vente_defaut du produit (EF-4.2).', max_digits=12)),
                ('stock_quantite', models.PositiveIntegerField(default=0, help_text='Quantité actuellement en stock dans cette agence.')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, help_text='Seuil sous lequel une alerte de stock bas est déclenchée (EF-4.4).')),
                ('actif', models.BooleanField(default=True, help_text="Une fiche inactive : ce produit n'est pas proposé par cette agence (EF-4.2).")),
                ('agence', models.ForeignKey(help_text='Agence concernée.', on_delete=django.db.models.deletion.CASCADE, related_name='produits_agence', to='general.agence')),
                ('produit', models.ForeignKey(help_text='Produit concerné.', on_delete=django.db.models.deletion.CASCADE, related_name='prix_stocks', to='products.produit')),
            ],
            options={
                'verbose_name': 'Prix & stock par agence',
                'verbose_name_plural': 'Prix & stocks par agence',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('quantite', models.PositiveIntegerField(help_text='Quantité à transférer.')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', help_text='Statut courant du transfert (EF-5.2).', max_length=20)),
                ('date_transfert', models.DateTimeField(blank=True, help_text='Date à laquelle le transfert a été finalisé.', null=True)),
                ('agence_destination', models.ForeignKey(help_text='Agence de destination du transfert.', on_delete=django.db.models.deletion.PROTECT, related_name='transferts_destination', to='general.agence')),
                ('agence_source', models.ForeignKey(help_text="Agence d'origine du transfert.", on_delete=django.db.models.deletion.PROTECT, related_name='transferts_source', to='general.agence')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
