# Generated by Django 5.2.16 on 2026-07-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertstock',
            name='approuve_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant approuvé le transfert, le cas échéant (EF-5.2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='demande_par',
            field=models.ForeignKey(help_text='Utilisateur ayant initié la demande de transfert (EF-5.1).', on_delete=django.db.models.deletion.PROTECT, related_name='transferts_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='produit',
            field=models.ForeignKey(help_text='Produit transféré.', on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='products.produit'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['parent', 'actif'], name='products_ca_parent__fd27fb_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'actif'], name='products_pr_categor_c7ea2f_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['sku'], name='products_pr_sku_8f5d43_idx'),
        ),
        migrations.AddIndex(
            model_name='produitagence',
            index=models.Index(fields=['agence', 'actif'], name='products_pr_agence__eb4a17_idx'),
        ),
        migrations.AddIndex(
            model_name='produitagence',
            index=models.Index(fields=['stock_quantite'], name='products_pr_stock_q_12f5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='produitagence',
            constraint=models.UniqueConstraint(fields=('produit', 'agence'), name='unique_produit_par_agence'),
        ),
        migrations.AddIndex(
            model_name='transfertstock',
            index=models.Index(fields=['statut', 'created_at'], name='products_tr_statut_10f3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='transfertstock',
            index=models.Index(fields=['agence_source', 'agence_destination'], name='products_tr_agence__44faeb_idx'),
        ),
    ]
