# Generated by Django 5.2.16 on 2026-07-30 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique (UUID) de l'enregistrement.", primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de création de l'enregistrement.")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification.')),
                ('fichier', models.FileField(help_text='Fichier Excel (.xlsx) contenant les catégories à importer.', upload_to='imports/categories/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec')], db_index=True, default='EN_ATTENTE', help_text='Statut courant du traitement.', max_length=20)),
                ('total_lignes', models.PositiveIntegerField(default=0, help_text='Nombre de lignes traitées (hors en-tête).')),
                ('lignes_reussies', models.PositiveIntegerField(default=0, help_text='Nombre de catégories créées ou mises à jour avec succès.')),
                ('lignes_echouees', models.PositiveIntegerField(default=0, help_text='Nombre de lignes en erreur (nom manquant, parent introuvable...).')),
                ('rapport', models.JSONField(blank=True, default=list, help_text='Détail ligne par ligne : [{ligne, nom, statut, message}, ...].')),
                ('importe_par', models.ForeignKey(blank=True, help_text='Utilisateur ayant lancé cet import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import de catégories',
                'verbose_name_plural': 'Imports de catégories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
